import 'bootstrap/dist/css/bootstrap.css';
import { Signika_Negative } from 'next/font/google'


const signikaNegative = Signika_Negative({ subsets: ['latin'], weight: ['400', '500', '700']})

export const metadata = {
  title: 'Weather Chart App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={signikaNegative.className}>{children}</body>
    </html>
  )
}
  